//%attributes = {"invisible":true}
ARRAY TEXT:C222(<>TESTASSERTIONSFAILURES_AT; 0)
ARRAY BOOLEAN:C223(<>TESTASSERTIONSPASSED_BOO; 0)
ARRAY TEXT:C222(<>TESTASSERTIONTESTNAMES_AT; 0)
ARRAY TEXT:C222(<>TESTNAMES_AT; 0)